from app.crud.audio import (
    create_audio,
    delete_audio,
    get_audio,
    list_audios,
    update_audio,
)
from app.crud.app_user import (
    create_app_user,
    get_app_user,
    get_app_user_by_mobile,
    get_app_user_by_wechat_openid,
    list_app_users,
)
from app.crud.rbac import (
    create_permission,
    create_role,
    create_user,
    ensure_role_permission,
    ensure_user_role,
    get_permission_by_code,
    get_role_by_code,
    get_user,
    get_user_by_username,
    get_user_permissions,
    list_permissions,
    list_roles,
    list_users,
    remove_role_permission,
    remove_user_role,
)
from app.crud.daily_quote import (
    create_daily_quote,
    get_daily_quote,
    get_daily_quote_by_date,
    list_daily_quotes,
    update_daily_quote,
    delete_daily_quote,
)
from app.crud.user_activity_record import (
    create_activity_record,
    get_activity_record,
    get_in_progress_activity,
    list_activity_records,
    update_activity_record,
    count_activities_today_by_type,
)
from app.crud.user_audio_playback import create_playback, get_playback, list_playbacks_for_user
from app.crud.user_sleep_record import create_sleep_record, get_sleep_record, list_sleep_records_for_user

__all__ = [
    "create_audio",
    "delete_audio",
    "get_audio",
    "list_audios",
    "update_audio",
    "create_app_user",
    "get_app_user",
    "get_app_user_by_mobile",
    "get_app_user_by_wechat_openid",
    "list_app_users",
    "create_permission",
    "create_role",
    "create_user",
    "ensure_role_permission",
    "ensure_user_role",
    "remove_user_role",
    "remove_role_permission",
    "get_user",
    "get_user_by_username",
    "get_user_permissions",
    "list_users",
    "get_role_by_code",
    "list_roles",
    "get_permission_by_code",
    "list_permissions",
    "create_sleep_record",
    "get_sleep_record",
    "list_sleep_records_for_user",
    "create_daily_quote",
    "get_daily_quote",
    "get_daily_quote_by_date",
    "list_daily_quotes",
    "update_daily_quote",
    "delete_daily_quote",
    "create_activity_record",
    "get_activity_record",
    "get_in_progress_activity",
    "list_activity_records",
    "update_activity_record",
    "count_activities_today_by_type",
    "create_playback",
    "get_playback",
    "list_playbacks_for_user",
]

